// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpB4kAX6byhAp53Z-m9chs9GYsplCbHBg',
    appId: '1:686819576656:web:fa9eb5d8fac4cd9f76ba55',
    messagingSenderId: '686819576656',
    projectId: 'eashion',
    authDomain: 'eashion.firebaseapp.com',
    databaseURL: 'https://eashion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eashion.firebasestorage.app',
    measurementId: 'G-WCRQ34FMFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rL2oaYi3tDkOg8P69Q05YK1X-gFXVMM',
    appId: '1:686819576656:android:e9cd761ae1126f4876ba55',
    messagingSenderId: '686819576656',
    projectId: 'eashion',
    databaseURL: 'https://eashion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eashion.firebasestorage.app',
  );
}
